export { reducer as intl } from './intl'
export { reducer as auth } from './auth'
export { reducer as notification } from './notifications'
export { reducer as product_category } from './product_categories'
export { nav } from './base/reducers'
export { dialog } from './base/reducers'
export { reducer as user } from './users'
export { reducer as product } from './products'
