export const RECEIVE_PRODUCT_CATEGORIES = 'RECEIVE_PRODUCT_CATEGORIES'
export const REQUEST_PRODUCT_CATEGORIES = 'REQUEST_PRODUCT_CATEGORIES'
export const DROP_FILE_PRODUCT_CATEGORIES = 'DROP_FILE_PRODUCT_CATEGORIES'
