// Pagination
export const SET_PAGINATION = 'SET_PAGINATION'

// Nav
export const TOGGLE_MOBILE_NAV = 'TOGGLE_MOBILE_NAV'
export const TOGGLE_DROPDOWN_LANGUAGES = 'TOGGLE_DROPDOWN_LANGUAGES'
export const SET_CURRENT_LINK = 'SET_CURRENT_LINK'
